--- #YAML:1.0
name:               Devel-PPPort
version:            3.16
abstract:           Perl/Pollution/Portability
author:
    - Marcus Holland-Moritz <mhx@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48_01
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
