--- #YAML:1.0
name:                Devel-PPPort
version:             3.14_01
abstract:            Perl/Pollution/Portability
license:             perl
author:              
    - Marcus Holland-Moritz <mhx@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
